DROP TABLE IF EXISTS `LIMS_USER`;
CREATE TABLE `LIMS_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(64) COLLATE utf8_unicode_ci NOT NULL COMMENT '用户名',
  `PASSWORD` varchar(256) COLLATE utf8_unicode_ci NOT NULL COMMENT '密码',
  `STATE` int(1) NOT NULL COMMENT '0-启用 1-禁用 2-锁定',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_USERNAME` (`USERNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;